<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends EntityRepository
{
    public function isExist($adresse)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a = :adresse')
                ->setParameter('adresse', $adresse)
            ->getQuery()
            ->getOneOrNullResult();

        return $qb;
    }
}
