<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function getListe()
    {
        return $this->createQueryBuilder('c')
            ->leftJoin('c.genre', 'g')
            ->addSelect('g')
            ->orderBy('g.nomGenre')
            ->addOrderBy('c.nomCategorie')
            ->getQuery()
            ->getResult();
    }

    public function findWithGenre($id)
    {
        return $this->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->leftJoin('c.genre', 'g')
            ->addSelect('g')
            ->getQuery()
            ->getSingleResult();
    }
}
