<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
    public function getListe()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.nomCollection')
            ->getQuery()
            ->getResult();
    }
}
