<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
    public function countAll()
    {
        return $this->createQueryBuilder('f')
            ->select('COUNT(f)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getListe($page, $maxParPage)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.commande', 'com')
            ->addSelect('com')
            ->setFirstResult(($page-1) * $maxParPage)
            ->setMaxResults($maxParPage)
            ->orderBy('f.id');

        return new Paginator($qb);
    }
}
