<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends EntityRepository
{
    public function getListe()
    {
        return $this->createQueryBuilder('f')
            ->orderBy('f.nomFormat')
            ->getQuery()
            ->getResult();
    }

    public function autocomplete($entree)
    {
        return $qb = $this->createQueryBuilder('f')
            ->select('f.nomFormat')
            ->where('f.nomFormat LIKE :entree')
                ->setParameter('entree', '%' . $entree . '%')
            ->setMaxResults(5)
            ->getQuery()
            ->getArrayResult();
    }
}
