<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
    public function getListe()
    {
        return $this->createQueryBuilder('g')
            ->orderBy('g.nomGenre')
            ->getQuery()
            ->getResult();
    }

    public function getListeAvecCategorie()
    {
        return $this->createQueryBuilder('g')
            ->leftjoin('g.categories', 'cat')
            ->addSelect('cat')
            ->leftJoin('cat.livres', 'liv')
            ->addSelect('liv')
            ->orderBy('g.nomGenre')
            ->getQuery()
            ->getResult();
    }
}
