<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function noteExist($livre, $utilisateur)
    {
        return $this->createQueryBuilder('n')
            ->where('n.livre = :livre')
                ->setParameter('livre', $livre)
            ->andWhere('n.utilisateur = :utilisateur')
                ->setParameter('utilisateur', $utilisateur)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
