<?php

namespace TFE\LibrairieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RecompenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecompenseRepository extends EntityRepository
{
    public function countAll()
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getListeComplete($page, $maxParPage)
    {
        $qb = $this
            ->createQueryBuilder('r')
            ->setFirstResult(($page-1) * $maxParPage)
            ->setMaxResults($maxParPage)
            ->orderBy('r.nomRecompense', 'ASC')
        ;

        return new Paginator($qb);
    }
}
