# chemin: /admin/format

admin_format_liste:
    path:     /
    defaults: { _controller: TFELibrairieBundle:AdminFormat:liste }

admin_format_ajouter:
    path:     /add
    defaults: { _controller: TFELibrairieBundle:AdminFormat:ajouter }

admin_format_modifier:
    path:     /update/{id}
    defaults: { _controller: TFELibrairieBundle:AdminFormat:modifier }
    requirements:
        id: \d*

admin_format_supprimer:
    path:     /delete/{id}
    defaults: { _controller: TFELibrairieBundle:AdminFormat:supprimer }
    requirements:
        id: \d*

