# chemin: /

# Pointeur vers le fichier gérant les routes de la partie admin
tfe_librairie_admin:
    resource: "@TFELibrairieBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

tfe_librairie_catalogue:
    resource: "@TFELibrairieBundle/Resources/config/routing_catalogue.yml"
    prefix:   /catalogue

tfe_librairie_news:
    resource: "@TFELibrairieBundle/Resources/config/routing_news.yml"
    prefix:   /news

tfe_librairie_livre:
    resource: "@TFELibrairieBundle/Resources/config/routing_livre.yml"
    prefix:   /livre

# Accueil du site
tfe_librairie_accueil:
    path:     /
    defaults: { _controller: TFELibrairieBundle:Accueil:index }

# Page A propos de nous
tfe_librairie_about_us:
    path:     /about-us
    defaults: { _controller: TFELibrairieBundle:Accueil:aboutUs }

# Panier *** A externaliser ***
tfe_librairie_panier_ajouter:
    path:     /panier/ajouter/{id}/{quantite}
    defaults: { _controller: TFELibrairieBundle:Panier:ajouter }
    requirements:
        id:       \d+
        quantite: \d+

tfe_librairie_panier_maj:
    path:     /panier/maj/{id}
    defaults: { _controller: TFELibrairieBundle:Panier:majLigneCommande }
    requirements:
        id:   \d+

tfe_librairie_panier_enlever:
    path:     /panier/enlever/{id}
    defaults: { _controller: TFELibrairieBundle:Panier:enlever }
    requirements:
        id:   \d+

tfe_librairie_panier_gestion:
    path:     /panier/gestion
    defaults: { _controller: TFELibrairieBundle:Panier:gestionPanier }

tfe_librairie_panier_connexion:
    path:     /panier/gestion/info
    defaults: { _controller: TFELibrairieBundle:Panier:connexion }

tfe_librairie_panier_envoi_paypal:
    path:     /panier/envoi/paypal
    defaults: { _controller: TFELibrairieBundle:Panier:EnvoiPaypal }

paypal_index:
    path:     /paypal/index
    defaults: { _controller: TFELibrairieBundle:PayPal:index }

paypal_success:
    path:     /paypal/success
    defaults: { _controller: TFELibrairieBundle:PayPal:succes }

paypal_cancel:
    path:     /paypal/cancel
    defaults: { _controller: TFELibrairieBundle:PayPal:cancel }

paypal_ipn:
    path:     /paypal/ipn
    defaults: { _controller: TFELibrairieBundle:PayPal:ipn }

conditions_generales_vente:
    path:     /cgv
    defaults: { _controller: TFELibrairieBundle:Accueil:cgv }

infos_personnelles:
    path:     /infos-personnelles
    defaults: { _controller: TFELibrairieBundle:Accueil:infosPersonnelles }

cookies_publicites:
    path:     /cookies-publicites
    defaults: { _controller: TFELibrairieBundle:Accueil:cookiesPublicités }

contact:
    path:     /contact
    defaults: { _controller: TFELibrairieBundle:Accueil:contact }